### PR TITLE
Fix #49: Redirect to original destination on login

### LINKED ISSUE #49: fix(auth): redirect to original destination on login
If you attempt to visit a page and don't have an active session. After logging in you're redirected to the dashboard instead of the page you originally were trying to visit.

### PR DESCRIPTION
**Pull request by forcemagic**
Hello there, devs of solder! :smile:

I'm eager to help out this project, and I would like to participate in the development process. This is my _entry PR_, and I'm willing to help out some more next year.

(PS: Happy new year :tada: ...almost)

### CODE REVIEW

**Comment by Indemnity83** [comment]
Awesome, thanks! 

Can you write tests for this behavior and add them to the PR?

**Comment by forcemagic** [comment]
I'm going to push a new change and let Travis test it because I'm having trouble with `php artisan dusk` (just hangs and times out, I can't even `dump()` after a `type()` call, but nvm)

**Comment by forcemagic** [comment]
Okay, I managed to get my setup working, and the test as well! Pushing it asap.

PS: Should I add feature tests too?

**Comment by Indemnity83** [comment]
Thanks!

**Pull request merged**
